### ISSUE TITLE
Wrong conversion for the equal sign

### ISSUE THREAD

**Issue by 2colours** [lizmat/HTML-Entities-Fast#1]
Hello,

apparently there are some problems with how the entity JSON used. There are conversions that consists of multiple codepoints, the notorious example being `&bne;` here - `(61 8421)`. It's simply generated as the first codepoint, that is, the equal sign, therefore equal signs can (and will) turn into `&bne;` rather than correctly to `&equals;`.

To avoid this, it would be good to use a list of codepoints rather than just one, or possibly use the grapheme-level representation on NQP level.

**Comment by lizmat** [comment]
Sorry, this issue has fallen through the cracks.

Release [0.0.5](https://raku.land/zef:lizmat/HTML::Entity::Fast?v=0.0.5) has this fixed.

Closing this issue now
