### ISSUE TITLE
Support for Numeric character references

### ISSUE THREAD

**Issue by demanuel** [lizmat/HTML-Entities-Fast#2]
Hi,

Is it possible to add support for numeric character references?

For example: `&lt; `  is the same as `&#60;` and the same as `&#x3C;`

More info about it here: https://www.w3.org/TR/html4/charset.html#h-5.3

Regards,
David

**Comment by lizmat** [comment]
Sorry this has fallen through the cracks.  :-(

Release [0.0.4](https://raku.land/zef:lizmat/HTML::Entity::Fast?v=0.0.4) now has support for `&#60;` and `&x3c`.

So closing this issue.
